### ISSUE TITLE
iView 升级至 ViewUI 4.0了, 何时可以适配?

### ISSUE THREAD

**Issue by Alvinpro** [xuliangzhan/vxe-table-plugin-iview#1]
在ViewUI 4.0上尝试安装了一下

npm install view-design --save
npm install xe-utils vxe-table vxe-table-plugin-iview --save

peerDependencies WARNING vxe-table-plugin-iview@* requires a peer of iview@>=3.0.0 but none was installed

引入之后http://localhost:8080/就白屏...

**Comment by Alvinpro** [comment]
只用 xe-utils vxe-table 和'vxe-table/lib/index.css' 显示正常, 一旦引按官方说明去掉'vxe-table/lib/index.css',引入vxe-table-plugin-iview, import 'vxe-table-plugin-iview/dist/style.css'
就好变成了如图,这是什么问题呀
![vxetable](https://user-images.githubusercontent.com/50291212/78457558-a8333680-76dd-11ea-81e6-1e6b4d803a57.png)

**Comment by xuliangzhan** [comment]
```javascript
import 'vxe-table/lib/index.css'
```
